# Generated by Django 2.1 on 2018-09-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_username', models.CharField(max_length=45)),
                ('a_passwd', models.CharField(max_length=45)),
                ('a_company', models.CharField(max_length=100)),
                ('a_tel', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folderame', models.CharField(max_length=45, verbose_name='文件名')),
                ('fpath', models.CharField(default='/home/voip/Projects/CQMB_Project/media/', max_length=60, unique=True)),
                ('modifytime', models.TimeField(default=django.utils.timezone.now)),
                ('filesize', models.CharField(default=0, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Nethost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('m_hostname', models.CharField(max_length=45, unique=True, verbose_name='主机名')),
                ('m_ip', models.CharField(max_length=45, unique=True, verbose_name='IP')),
                ('m_port', models.CharField(max_length=30, verbose_name='端口')),
                ('m_username', models.CharField(max_length=45, verbose_name='用户名')),
                ('m_passwd', models.CharField(max_length=45, verbose_name='密码')),
                ('m_company', models.CharField(max_length=45, verbose_name='厂商')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, verbose_name='类型')),
                ('content', models.TextField(verbose_name='修改详情')),
                ('username', models.CharField(max_length=45, verbose_name='用户名')),
                ('url', models.CharField(max_length=45, verbose_name='操作方法')),
                ('time', models.DateTimeField(max_length=45, verbose_name='时间')),
                ('value', models.CharField(max_length=45, null=True, verbose_name='cmd')),
            ],
        ),
        migrations.CreateModel(
            name='Sysinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('osname', models.CharField(max_length=45, verbose_name='os')),
                ('cpu', models.CharField(max_length=45, verbose_name='cpu')),
                ('mem', models.CharField(max_length=45, verbose_name='mem')),
                ('hdisk', models.CharField(max_length=45, verbose_name='hdisk')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=60, null=True, verbose_name='tsaskid')),
                ('task_status', models.CharField(max_length=60, null=True, verbose_name='task_status')),
                ('hostname', models.CharField(max_length=45, verbose_name='主机名')),
                ('ip', models.CharField(max_length=45, verbose_name='IP')),
                ('port', models.CharField(max_length=30, verbose_name='端口')),
                ('username', models.CharField(max_length=45, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=45, verbose_name='密码')),
                ('taskcmd', models.CharField(max_length=100, verbose_name='cmd')),
                ('tasktime', models.DateTimeField(max_length=45, null=True, verbose_name='时间')),
                ('company', models.CharField(max_length=45, verbose_name='厂商')),
            ],
        ),
        migrations.AddField(
            model_name='floder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqen.Nethost', to_field='m_hostname'),
        ),
        migrations.AddField(
            model_name='downloadpath',
            name='ppath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqen.Floder', to_field='fpath'),
        ),
    ]
