# Generated by Django 2.1.2 on 2018-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floder',
            name='filename',
            field=models.CharField(max_length=45, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='floder',
            name='folderame',
            field=models.CharField(max_length=45, verbose_name='文件夹名'),
        ),
    ]
