# Generated by Django 2.1.2 on 2018-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqen', '0002_auto_20181011_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floder',
            name='filename',
            field=models.CharField(max_length=500, null=True, verbose_name='文件名'),
        ),
    ]
