# Generated by Django 2.1.2 on 2018-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqen', '0003_auto_20181011_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floder',
            name='fpath',
            field=models.CharField(default='/media/', max_length=60, unique=True),
        ),
    ]
